#!/bin/bash

# Script to update Kong JWT secret to match backend JWT_SECRET
# This ensures Kong can validate JWTs generated by the backend

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Kong JWT Secret Update Script${NC}"
echo -e "${GREEN}========================================${NC}"

# Check for JWT_SECRET argument
if [ -z "$1" ]; then
    echo -e "${YELLOW}Usage: $0 <JWT_SECRET>${NC}"
    echo -e "${YELLOW}Example: $0 'your-secret-key-here'${NC}"
    echo ""
    echo -e "${YELLOW}Current backend JWT secret locations:${NC}"
    echo "  • backend/src/main/resources/application.properties"
    echo "  • k8s/backend-deployment.yaml (environment variable)"
    echo ""
    exit 1
fi

JWT_SECRET="$1"

# Validate secret length (HS256 requires at least 256 bits = 32 bytes)
if [ ${#JWT_SECRET} -lt 32 ]; then
    echo -e "${RED}Warning: JWT secret should be at least 32 characters for HS256${NC}"
    read -p "Continue anyway? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

echo -e "\n${YELLOW}Updating Kong declarative configuration...${NC}"

# Backup current config
cp k8s/kong/kong-declarative-config.yaml k8s/kong/kong-declarative-config.yaml.backup
echo -e "${GREEN}✓ Backup created: kong-declarative-config.yaml.backup${NC}"

# Update the secret in the YAML file
# Using sed to replace the secret value
sed -i "s|secret: .*|secret: ${JWT_SECRET}|g" k8s/kong/kong-declarative-config.yaml

echo -e "${GREEN}✓ Configuration updated${NC}"

echo -e "\n${YELLOW}Applying updated configuration to Kubernetes...${NC}"
kubectl apply -f k8s/kong/kong-declarative-config.yaml

echo -e "\n${YELLOW}Restarting Kong Gateway to apply changes...${NC}"
kubectl rollout restart deployment/kong

echo -e "\n${YELLOW}Waiting for Kong to be ready...${NC}"
kubectl rollout status deployment/kong --timeout=120s

echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}Kong JWT Secret Updated Successfully!${NC}"
echo -e "${GREEN}========================================${NC}"

echo -e "\n${YELLOW}Verification:${NC}"
echo "  1. Test login: curl -X POST http://localhost:30080/api/auth/login -H 'Content-Type: application/json' -d '{\"email\":\"...\",\"password\":\"...\"}'"
echo "  2. Use returned JWT to access protected endpoints"
echo "  3. Check Kong logs if issues: kubectl logs -l app=kong --tail=50"

echo -e "\n${YELLOW}Note:${NC} Ensure backend also uses the same JWT_SECRET"
